`timescale 1ns/1ps

// Generated by gen_trit5_lut.py; do not edit entries manually.
// Key assignment mode: low_switch_sparse
//
// Output ordering:
//   sign_o[j]          : j-th non-zero sign in original coordinate order
//                        0 = -1, 1 = +1; unused bits are 0
//   count_o            : number of meaningful sign/coordinate entries
//   coord_o[3*j +: 3] : original coordinate (0..4) for sign_o[j]
//                        unused coordinate fields are 0
module trit5_decode_lut (
    input  logic [7:0]  key_i,
    output logic        valid_o,
    output logic [4:0]  sign_o,
    output logic [2:0]  count_o,
    output logic [14:0] coord_o
);

    always_comb begin
        valid_o = 1'b0;
        sign_o  = 5'b0;
        count_o = 3'd0;
        coord_o = 15'b0;

        case (key_i)
            8'h00: begin // id=  0, w=(0,0,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd0;
                coord_o = 15'h0000;
            end
            8'h01: begin // id=  1, w=(-1,0,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd1;
                coord_o = 15'h0000;
            end
            8'h02: begin // id=  2, w=(+1,0,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd1;
                coord_o = 15'h0000;
            end
            8'h03: begin // id= 81, w=(0,0,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd1;
                coord_o = 15'h0004;
            end
            8'h04: begin // id=  3, w=(0,-1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd1;
                coord_o = 15'h0001;
            end
            8'h05: begin // id=162, w=(0,0,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd1;
                coord_o = 15'h0004;
            end
            8'h06: begin // id=  4, w=(-1,-1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0008;
            end
            8'h07: begin // id= 84, w=(0,-1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0021;
            end
            8'h08: begin // id=  6, w=(0,+1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd1;
                coord_o = 15'h0001;
            end
            8'h09: begin // id=  5, w=(+1,-1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0008;
            end
            8'h0A: begin // id=  7, w=(-1,+1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0008;
            end
            8'h0B: begin // id= 87, w=(0,+1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0021;
            end
            8'h0C: begin // id=  8, w=(+1,+1,0,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0008;
            end
            8'h0D: begin // id= 90, w=(0,0,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0022;
            end
            8'h0E: begin // id= 99, w=(0,0,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0022;
            end
            8'h0F: begin // id=102, w=(0,-1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h10: begin // id=  9, w=(0,0,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd1;
                coord_o = 15'h0002;
            end
            8'h11: begin // id= 10, w=(-1,0,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0010;
            end
            8'h12: begin // id= 11, w=(+1,0,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0010;
            end
            8'h13: begin // id=108, w=(0,0,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0023;
            end
            8'h14: begin // id= 12, w=(0,-1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0011;
            end
            8'h15: begin // id=135, w=(0,0,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0023;
            end
            8'h16: begin // id=163, w=(-1,0,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0020;
            end
            8'h17: begin // id=105, w=(0,+1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h18: begin // id= 15, w=(0,+1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0011;
            end
            8'h19: begin // id=164, w=(+1,0,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0020;
            end
            8'h1A: begin // id=165, w=(0,-1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0021;
            end
            8'h1B: begin // id=109, w=(-1,0,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h1C: begin // id=168, w=(0,+1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0021;
            end
            8'h1D: begin // id=110, w=(+1,0,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h1E: begin // id=111, w=(0,-1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h1F: begin // id=127, w=(-1,0,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h20: begin // id= 18, w=(0,0,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd1;
                coord_o = 15'h0002;
            end
            8'h21: begin // id= 19, w=(-1,0,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0010;
            end
            8'h22: begin // id= 20, w=(+1,0,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0010;
            end
            8'h23: begin // id=171, w=(0,0,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0022;
            end
            8'h24: begin // id= 21, w=(0,-1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0011;
            end
            8'h25: begin // id=180, w=(0,0,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0022;
            end
            8'h26: begin // id=189, w=(0,0,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0023;
            end
            8'h27: begin // id=114, w=(0,+1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h28: begin // id= 24, w=(0,+1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0011;
            end
            8'h29: begin // id=216, w=(0,0,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0023;
            end
            8'h2A: begin // id= 13, w=(-1,-1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h2B: begin // id=117, w=(0,0,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h2C: begin // id= 14, w=(+1,-1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h2D: begin // id=126, w=(0,0,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h2E: begin // id=136, w=(-1,0,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h2F: begin // id=128, w=(+1,0,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h30: begin // id= 28, w=(-1,0,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0018;
            end
            8'h31: begin // id= 16, w=(-1,+1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h32: begin // id= 17, w=(+1,+1,-1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h33: begin // id=137, w=(+1,0,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h34: begin // id= 22, w=(-1,-1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h35: begin // id=138, w=(0,-1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h36: begin // id=141, w=(0,+1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h37: begin // id=129, w=(0,-1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h38: begin // id= 23, w=(+1,-1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h39: begin // id=144, w=(0,0,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h3A: begin // id=153, w=(0,0,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h3B: begin // id=132, w=(0,+1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h3C: begin // id=166, w=(-1,-1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'h3D: begin // id=139, w=(-1,-1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h3E: begin // id=140, w=(+1,-1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h3F: begin // id=148, w=(-1,-1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h40: begin // id= 27, w=(0,0,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd1;
                coord_o = 15'h0003;
            end
            8'h41: begin // id= 29, w=(+1,0,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0018;
            end
            8'h42: begin // id= 30, w=(0,-1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0019;
            end
            8'h43: begin // id= 25, w=(-1,+1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h44: begin // id= 33, w=(0,+1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0019;
            end
            8'h45: begin // id= 26, w=(+1,+1,+1,0,0)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0088;
            end
            8'h46: begin // id= 31, w=(-1,-1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h47: begin // id=167, w=(+1,-1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'h48: begin // id= 36, w=(0,0,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h001A;
            end
            8'h49: begin // id= 32, w=(+1,-1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h4A: begin // id= 34, w=(-1,+1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h4B: begin // id=169, w=(-1,+1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'h4C: begin // id= 35, w=(+1,+1,0,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h4D: begin // id=170, w=(+1,+1,0,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'h4E: begin // id=172, w=(-1,0,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'h4F: begin // id=142, w=(-1,+1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h50: begin // id= 45, w=(0,0,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h001A;
            end
            8'h51: begin // id= 37, w=(-1,0,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h52: begin // id= 38, w=(+1,0,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h53: begin // id=173, w=(+1,0,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'h54: begin // id= 39, w=(0,-1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h55: begin // id=174, w=(0,-1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h56: begin // id=177, w=(0,+1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h57: begin // id=143, w=(+1,+1,0,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h58: begin // id= 42, w=(0,+1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h59: begin // id=181, w=(-1,0,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'h5A: begin // id=182, w=(+1,0,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'h5B: begin // id=145, w=(-1,0,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h5C: begin // id=183, w=(0,-1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h5D: begin // id=146, w=(+1,0,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h5E: begin // id=147, w=(0,-1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h5F: begin // id=149, w=(+1,-1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h60: begin // id= 55, w=(-1,0,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0018;
            end
            8'h61: begin // id= 46, w=(-1,0,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h62: begin // id= 47, w=(+1,0,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h63: begin // id=186, w=(0,+1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'h64: begin // id= 48, w=(0,-1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h65: begin // id=190, w=(-1,0,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h66: begin // id=191, w=(+1,0,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h67: begin // id=150, w=(0,+1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h68: begin // id= 51, w=(0,+1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h69: begin // id=192, w=(0,-1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h6A: begin // id=195, w=(0,+1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h6B: begin // id=154, w=(-1,0,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h6C: begin // id=198, w=(0,0,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h6D: begin // id=155, w=(+1,0,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'h6E: begin // id=156, w=(0,-1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h6F: begin // id=151, w=(-1,+1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h70: begin // id= 58, w=(-1,-1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h71: begin // id=207, w=(0,0,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h72: begin // id=217, w=(-1,0,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h73: begin // id=159, w=(0,+1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'h74: begin // id=218, w=(+1,0,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0118;
            end
            8'h75: begin // id=175, w=(-1,-1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h76: begin // id=176, w=(+1,-1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h77: begin // id=152, w=(+1,+1,-1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h78: begin // id=219, w=(0,-1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h79: begin // id=178, w=(-1,+1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h7A: begin // id=179, w=(+1,+1,-1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h7B: begin // id=157, w=(-1,-1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h7C: begin // id=184, w=(-1,-1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h7D: begin // id=158, w=(+1,-1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h7E: begin // id=160, w=(-1,+1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'h80: begin // id= 54, w=(0,0,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd1;
                coord_o = 15'h0003;
            end
            8'h81: begin // id= 56, w=(+1,0,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0018;
            end
            8'h82: begin // id= 57, w=(0,-1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h0019;
            end
            8'h83: begin // id= 59, w=(+1,-1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h84: begin // id= 60, w=(0,+1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h0019;
            end
            8'h85: begin // id= 61, w=(-1,+1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h86: begin // id= 62, w=(+1,+1,0,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h00C8;
            end
            8'h87: begin // id=222, w=(0,+1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h0119;
            end
            8'h88: begin // id= 63, w=(0,0,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd2;
                coord_o = 15'h001A;
            end
            8'h89: begin // id= 64, w=(-1,0,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h8A: begin // id= 65, w=(+1,0,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h8B: begin // id=225, w=(0,0,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h8C: begin // id= 66, w=(0,-1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h8D: begin // id=234, w=(0,0,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h011A;
            end
            8'h8E: begin // id= 40, w=(-1,-1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h8F: begin // id=185, w=(+1,-1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h90: begin // id= 72, w=(0,0,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd2;
                coord_o = 15'h001A;
            end
            8'h91: begin // id= 69, w=(0,+1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h92: begin // id= 73, w=(-1,0,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h93: begin // id= 41, w=(+1,-1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h94: begin // id= 74, w=(+1,0,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h00D0;
            end
            8'h95: begin // id= 43, w=(-1,+1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h96: begin // id= 44, w=(+1,+1,-1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h97: begin // id=187, w=(-1,+1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h98: begin // id= 75, w=(0,-1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'h99: begin // id= 49, w=(-1,-1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h9A: begin // id= 50, w=(+1,-1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h9B: begin // id=188, w=(+1,+1,+1,0,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'h9C: begin // id= 52, w=(-1,+1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'h9D: begin // id=193, w=(-1,-1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h9E: begin // id=194, w=(+1,-1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'h9F: begin // id=161, w=(+1,+1,+1,+1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hA0: begin // id= 82, w=(-1,0,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd2;
                coord_o = 15'h0020;
            end
            8'hA1: begin // id= 78, w=(0,+1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd3;
                coord_o = 15'h00D1;
            end
            8'hA2: begin // id= 85, w=(-1,-1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'hA3: begin // id= 53, w=(+1,+1,+1,-1,0)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hA4: begin // id= 86, w=(+1,-1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'hA5: begin // id= 67, w=(-1,-1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hA6: begin // id= 68, w=(+1,-1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hA7: begin // id=196, w=(-1,+1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hA8: begin // id= 88, w=(-1,+1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'hA9: begin // id= 70, w=(-1,+1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hAA: begin // id= 71, w=(+1,+1,-1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hAB: begin // id=197, w=(+1,+1,0,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hAC: begin // id= 76, w=(-1,-1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hAD: begin // id=199, w=(-1,0,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hAE: begin // id=200, w=(+1,0,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hAF: begin // id=202, w=(-1,-1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10000;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hB0: begin // id= 89, w=(+1,+1,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0108;
            end
            8'hB1: begin // id= 77, w=(+1,-1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hB2: begin // id= 79, w=(-1,+1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hB3: begin // id=201, w=(0,-1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01000;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hB4: begin // id= 80, w=(+1,+1,+1,+1,0)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd4;
                coord_o = 15'h0688;
            end
            8'hB5: begin // id=204, w=(0,+1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01001;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hB6: begin // id=208, w=(-1,0,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hB7: begin // id=203, w=(+1,-1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10001;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hB8: begin // id= 94, w=(-1,-1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hB9: begin // id=209, w=(+1,0,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hBA: begin // id=210, w=(0,-1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01010;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hBB: begin // id=205, w=(-1,+1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10010;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hBC: begin // id=213, w=(0,+1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01011;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hBD: begin // id=206, w=(+1,+1,-1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10011;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hBE: begin // id=211, w=(-1,-1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10100;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hC0: begin // id= 83, w=(+1,0,0,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd2;
                coord_o = 15'h0020;
            end
            8'hC1: begin // id= 91, w=(-1,0,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'hC2: begin // id= 92, w=(+1,0,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'hC3: begin // id= 95, w=(+1,-1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hC4: begin // id= 93, w=(0,-1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'hC5: begin // id= 97, w=(-1,+1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hC6: begin // id= 98, w=(+1,+1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hC7: begin // id=220, w=(-1,-1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hC8: begin // id= 96, w=(0,+1,-1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd3;
                coord_o = 15'h0111;
            end
            8'hC9: begin // id=103, w=(-1,-1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hCA: begin // id=104, w=(+1,-1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hCB: begin // id=221, w=(+1,-1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hCC: begin // id=106, w=(-1,+1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hCD: begin // id=223, w=(-1,+1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hCE: begin // id=224, w=(+1,+1,0,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hCF: begin // id=212, w=(+1,-1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10101;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hD0: begin // id=100, w=(-1,0,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'hD1: begin // id=107, w=(+1,+1,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd4;
                coord_o = 15'h0888;
            end
            8'hD2: begin // id=112, w=(-1,-1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hD3: begin // id=226, w=(-1,0,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hD4: begin // id=113, w=(+1,-1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hD5: begin // id=227, w=(+1,0,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hD6: begin // id=228, w=(0,-1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01100;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hD7: begin // id=214, w=(-1,+1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10110;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hD8: begin // id=115, w=(-1,+1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hD9: begin // id=231, w=(0,+1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01101;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hDA: begin // id=235, w=(-1,0,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hDB: begin // id=215, w=(+1,+1,+1,-1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b10111;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hDC: begin // id=236, w=(+1,0,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hDD: begin // id=229, w=(-1,-1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11000;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hDE: begin // id=230, w=(+1,-1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11001;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hE0: begin // id=101, w=(+1,0,+1,0,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd3;
                coord_o = 15'h0110;
            end
            8'hE1: begin // id=116, w=(+1,+1,0,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd4;
                coord_o = 15'h08C8;
            end
            8'hE2: begin // id=118, w=(-1,0,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hE3: begin // id=237, w=(0,-1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01110;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hE4: begin // id=119, w=(+1,0,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd4;
                coord_o = 15'h08D0;
            end
            8'hE5: begin // id=240, w=(0,+1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b01111;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hE6: begin // id=121, w=(-1,-1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hE7: begin // id=232, w=(-1,+1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11010;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hE8: begin // id=120, w=(0,-1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00000;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hE9: begin // id=122, w=(+1,-1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hEA: begin // id=124, w=(-1,+1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00010;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hEB: begin // id=233, w=(+1,+1,-1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11011;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hEC: begin // id=125, w=(+1,+1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00011;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hED: begin // id=238, w=(-1,-1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11100;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hEE: begin // id=239, w=(+1,-1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11101;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF0: begin // id=123, w=(0,+1,-1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00001;
                count_o = 3'd4;
                coord_o = 15'h08D1;
            end
            8'hF1: begin // id=130, w=(-1,-1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00100;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF2: begin // id=131, w=(+1,-1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00101;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF3: begin // id=241, w=(-1,+1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11110;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF4: begin // id=133, w=(-1,+1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00110;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF5: begin // id=242, w=(+1,+1,+1,+1,+1)
                valid_o = 1'b1;
                sign_o  = 5'b11111;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            8'hF8: begin // id=134, w=(+1,+1,+1,-1,-1)
                valid_o = 1'b1;
                sign_o  = 5'b00111;
                count_o = 3'd5;
                coord_o = 15'h4688;
            end
            default: begin
                // 13 unused 8-bit keys: valid_o remains 0.
            end
        endcase
    end

endmodule
